"use client";

import { useDashboardState, type ActionItem } from "@/context/DashboardStateContext";
import { useState } from "react";
import {
  Sparkles,
  User,
  Calendar,
  AlertTriangle,
  Plus,
  Trash2,
  CheckCircle,
  HelpCircle,
  FileText,
  Clock,
  X,
  ChevronLeft,
  ChevronRight,
  Filter,
} from "lucide-react";


type TaskStatus = "TO_DO" | "IN_PROGRESS" | "BLOCKED" | "DONE";

interface KanbanItem extends ActionItem {
  status: TaskStatus;
}

function Page() {
  const { actionItems, addActionItem, updateActionItem, deleteActionItem, toggleActionItem } =
    useDashboardState();

  const [filterOwner, setFilterOwner] = useState("All");
  const [showAddModal, setShowAddModal] = useState(false);
  const [newTask, setNewTask] = useState({
    title: "",
    owner: "Founder",
    deadline: "",
    notes: "",
  });

  // Local helper to determine status based on 'done' and simple attributes
  // In a real database, we would have a status field. For this mock, we map:
  // - done: true -> DONE
  // - done: false + specific notes/mock -> TO_DO, IN_PROGRESS, BLOCKED
  const getTaskStatus = (t: ActionItem): TaskStatus => {
    if (t.done) return "DONE";
    if (t.notes?.includes("Blocked") || t.title.includes("URGENT")) return "BLOCKED";
    if (t.title.includes("Prep") || t.title.includes("Draft")) return "IN_PROGRESS";
    return "TO_DO";
  };

  const handleUpdateStatus = (id: string, currentStatus: TaskStatus, direction: "next" | "prev") => {
    const sequence: TaskStatus[] = ["TO_DO", "IN_PROGRESS", "BLOCKED", "DONE"];
    const idx = sequence.indexOf(currentStatus);
    let nextIdx = idx;

    if (direction === "next" && idx < sequence.length - 1) {
      nextIdx = idx + 1;
    } else if (direction === "prev" && idx > 0) {
      nextIdx = idx - 1;
    }

    const targetStatus = sequence[nextIdx];
    
    // Sync with global 'done' boolean
    if (targetStatus === "DONE") {
      updateActionItem(id, { done: true, notes: "Marked as Done." });
    } else {
      let notes = "";
      if (targetStatus === "BLOCKED") notes = "Blocked: awaiting feedback.";
      if (targetStatus === "IN_PROGRESS") notes = "In progress.";
      updateActionItem(id, { done: false, notes });
    }
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTask.title || !newTask.deadline) return;

    addActionItem(
      newTask.title,
      newTask.owner,
      newTask.deadline,
      "Manual",
      undefined,
      newTask.notes
    );

    setNewTask({ title: "", owner: "Founder", deadline: "", notes: "" });
    setShowAddModal(false);
  };

  // Get list of unique owners
  const owners = Array.from(new Set(actionItems.map((i) => i.owner)));

  // Filter tasks
  const filteredItems = actionItems.filter((i) => {
    if (filterOwner !== "All" && i.owner !== filterOwner) return false;
    return true;
  });

  const columns: { id: TaskStatus; label: string; border: string; bg: string }[] = [
    { id: "TO_DO", label: "To Do", border: "border-neutral-200", bg: "bg-neutral-50/50" },
    { id: "IN_PROGRESS", label: "In Progress", border: "border-blue-200", bg: "bg-blue-50/10" },
    { id: "BLOCKED", label: "Blocked", border: "border-red-200", bg: "bg-red-50/10" },
    { id: "DONE", label: "Done", border: "border-emerald-200", bg: "bg-emerald-50/15" },
  ];

  const isOverdue = (dateStr: string) => {
    return new Date(dateStr) < new Date() && dateStr !== "";
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header bar */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-[color:var(--t10-navy)]">Action Plans</h2>
          <p className="text-sm text-[color:var(--t10-grey)]">
            Track business actions generated by Zyne VC diagnostics and expert reviews.
          </p>
        </div>
        <div className="flex gap-2">
          {/* Owner Filter dropdown */}
          <div className="flex items-center gap-1.5 rounded-lg border border-[color:var(--t10-border)] bg-white px-3 py-1.5 text-xs text-[color:var(--t10-navy)]">
            <Filter className="h-3.5 w-3.5" />
            <select
              value={filterOwner}
              onChange={(e) => setFilterOwner(e.target.value)}
              className="bg-transparent font-medium outline-none cursor-pointer"
            >
              <option value="All">All Owners</option>
              {owners.map((o) => (
                <option key={o} value={o}>
                  {o}
                </option>
              ))}
            </select>
          </div>
          <button
            onClick={() => setShowAddModal(true)}
            className="inline-flex items-center gap-1 rounded-lg bg-[color:var(--t10-emerald)] px-4 py-2 text-xs font-bold text-white hover:bg-[color:var(--t10-green)] transition-all shadow"
          >
            <Plus className="h-4 w-4" /> Add Task
          </button>
        </div>
      </div>

      {/* Kanban Board Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {columns.map((col) => {
          const colTasks = filteredItems.filter((t) => getTaskStatus(t) === col.id);

          return (
            <div
              key={col.id}
              className={`rounded-2xl border ${col.border} ${col.bg} p-4 flex flex-col h-[500px] overflow-hidden`}
            >
              {/* Column Header */}
              <div className="flex justify-between items-center pb-3 border-b border-[color:var(--t10-border)] mb-3">
                <span className="text-xs font-bold text-[color:var(--t10-navy)] uppercase tracking-wider">
                  {col.label}
                </span>
                <span className="rounded-full bg-white border border-[color:var(--t10-border)] px-2 py-0.5 text-[10px] font-bold text-[color:var(--t10-grey)]">
                  {colTasks.length}
                </span>
              </div>

              {/* Tasks List */}
              <div className="flex-1 overflow-y-auto space-y-3 pr-1">
                {colTasks.map((task) => {
                  const overdue = isOverdue(task.deadline) && col.id !== "DONE";
                  return (
                    <div
                      key={task.id}
                      className="rounded-xl border border-[color:var(--t10-border)] bg-white p-3.5 shadow-sm space-y-3 hover:shadow transition-all animate-fade-in"
                    >
                      {/* Task title */}
                      <p className="text-xs font-bold text-[color:var(--t10-navy)] leading-relaxed">
                        {task.title}
                      </p>

                      {/* Notes / description */}
                      {task.notes && (
                        <p className="text-[10px] text-[color:var(--t10-grey)] leading-normal italic">
                          {task.notes}
                        </p>
                      )}

                      {/* Meta information */}
                      <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-neutral-100 text-[10px] text-[color:var(--t10-grey)]">
                        <span className="inline-flex items-center gap-1 bg-neutral-100 px-1.5 py-0.5 rounded font-semibold text-[color:var(--t10-navy)]">
                          <User className="h-3 w-3" /> {task.owner}
                        </span>

                        <span className={`inline-flex items-center gap-1 font-semibold ${overdue ? "text-red-600 animate-pulse" : ""}`}>
                          <Calendar className="h-3 w-3" /> {task.deadline}
                        </span>
                      </div>

                      {/* Origin tag & Action tools */}
                      <div className="flex items-center justify-between gap-2 border-t border-neutral-100 pt-2.5">
                        {/* Origin badge */}
                        <span className="inline-flex items-center gap-1 rounded bg-[color:var(--t10-mint)] px-1.5 py-0.5 text-[9px] font-bold text-[color:var(--t10-navy)]">
                          {task.source === "Zyne" && <Sparkles className="h-2.5 w-2.5 text-[color:var(--t10-emerald)]" />}
                          {task.source === "Expert" && <Clock className="h-2.5 w-2.5 text-blue-500" />}
                          {task.source} origin
                        </span>

                        {/* Move buttons */}
                        <div className="flex gap-1">
                          <button
                            onClick={() => deleteActionItem(task.id)}
                            className="p-1 hover:text-red-500 rounded transition-colors"
                            title="Delete Task"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                          <button
                            onClick={() => handleUpdateStatus(task.id, col.id, "prev")}
                            disabled={col.id === "TO_DO"}
                            className="p-1 hover:bg-neutral-100 disabled:opacity-30 rounded transition-colors"
                          >
                            <ChevronLeft className="h-3.5 w-3.5" />
                          </button>
                          <button
                            onClick={() => handleUpdateStatus(task.id, col.id, "next")}
                            disabled={col.id === "DONE"}
                            className="p-1 hover:bg-neutral-100 disabled:opacity-30 rounded transition-colors"
                          >
                            <ChevronRight className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}

                {colTasks.length === 0 && (
                  <p className="text-[11px] text-[color:var(--t10-grey)] italic text-center py-6">
                    Empty column
                  </p>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Add Task Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-sm animate-fade-in">
          <div className="max-w-md w-full rounded-2xl border border-[color:var(--t10-border)] bg-white p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-[color:var(--t10-border)] pb-3">
              <h3 className="text-sm font-bold text-[color:var(--t10-navy)]">Create Custom Action Item</h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="rounded-full p-1 hover:bg-neutral-100"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <form onSubmit={handleAddTask} className="space-y-4 text-xs">
              <label className="block">
                <span className="mb-1 block font-semibold text-[color:var(--t10-navy)]">Task Description</span>
                <input
                  type="text"
                  required
                  value={newTask.title}
                  onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  placeholder="e.g. Audit iMile shipping invoice parameters"
                  className="w-full rounded-md border border-[color:var(--t10-border)] px-3 py-2"
                />
              </label>

              <div className="grid grid-cols-2 gap-4">
                <label className="block">
                  <span className="mb-1 block font-semibold text-[color:var(--t10-navy)]">Assign Owner</span>
                  <select
                    value={newTask.owner}
                    onChange={(e) => setNewTask({ ...newTask, owner: e.target.value })}
                    className="w-full rounded-md border border-[color:var(--t10-border)] bg-white px-3 py-2"
                  >
                    <option value="Founder">Founder</option>
                    <option value="Ops">Ops Team</option>
                    <option value="Finance">Finance Team</option>
                    <option value="Zyne">Zyne AI Partner</option>
                  </select>
                </label>
                <label className="block">
                  <span className="mb-1 block font-semibold text-[color:var(--t10-navy)]">Deadline</span>
                  <input
                    type="date"
                    required
                    value={newTask.deadline}
                    onChange={(e) => setNewTask({ ...newTask, deadline: e.target.value })}
                    className="w-full rounded-md border border-[color:var(--t10-border)] px-3 py-2"
                  />
                </label>
              </div>

              <label className="block">
                <span className="mb-1 block font-semibold text-[color:var(--t10-navy)]">Strategic Notes (optional)</span>
                <textarea
                  rows={2}
                  value={newTask.notes}
                  onChange={(e) => setNewTask({ ...newTask, notes: e.target.value })}
                  placeholder="Additional context or links."
                  className="w-full rounded-md border border-[color:var(--t10-border)] p-2"
                />
              </label>

              <button
                type="submit"
                className="w-full rounded-lg bg-[color:var(--t10-emerald)] py-2 text-center text-xs font-bold text-white hover:bg-[color:var(--t10-green)] transition-all shadow"
              >
                Create Task
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default Page;
