/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZyneRouteImport } from './routes/zyne'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RecordingConfidentialityRouteImport } from './routes/recording-confidentiality'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumAdvisoryRouteImport } from './routes/premium-advisory'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommandCentreRouteImport } from './routes/command-centre'
import { Route as BookDiscoveryCallRouteImport } from './routes/book-discovery-call'
import { Route as AdvisoryAreasRouteImport } from './routes/advisory-areas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ExpertsSlugRouteImport } from './routes/experts.$slug'
import { Route as DashboardZyneRouteImport } from './routes/dashboard.zyne'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard.sessions'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardBusinessProfileRouteImport } from './routes/dashboard.business-profile'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAdvisorsRouteImport } from './routes/dashboard.advisors'
import { Route as DashboardActionPlansRouteImport } from './routes/dashboard.action-plans'
import { Route as AdvisoryAreasSlugRouteImport } from './routes/advisory-areas.$slug'

const ZyneRoute = ZyneRouteImport.update({
  id: '/zyne',
  path: '/zyne',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingConfidentialityRoute =
  RecordingConfidentialityRouteImport.update({
    id: '/recording-confidentiality',
    path: '/recording-confidentiality',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumAdvisoryRoute = PremiumAdvisoryRouteImport.update({
  id: '/premium-advisory',
  path: '/premium-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCentreRoute = CommandCentreRouteImport.update({
  id: '/command-centre',
  path: '/command-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDiscoveryCallRoute = BookDiscoveryCallRouteImport.update({
  id: '/book-discovery-call',
  path: '/book-discovery-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryAreasRoute = AdvisoryAreasRouteImport.update({
  id: '/advisory-areas',
  path: '/advisory-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ExpertsSlugRoute = ExpertsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExpertsRoute,
} as any)
const DashboardZyneRoute = DashboardZyneRouteImport.update({
  id: '/zyne',
  path: '/zyne',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessProfileRoute =
  DashboardBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdvisorsRoute = DashboardAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActionPlansRoute = DashboardActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => DashboardRoute,
} as any)
const AdvisoryAreasSlugRoute = AdvisoryAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdvisoryAreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/advisory-areas/$slug'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/contact'
    | '/cookies'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/advisory-areas/$slug'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/advisory-areas/$slug'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryAreasRoute: typeof AdvisoryAreasRouteWithChildren
  BookDiscoveryCallRoute: typeof BookDiscoveryCallRoute
  CommandCentreRoute: typeof CommandCentreRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExpertsRoute: typeof ExpertsRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  PremiumAdvisoryRoute: typeof PremiumAdvisoryRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordingConfidentialityRoute: typeof RecordingConfidentialityRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ZyneRoute: typeof ZyneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zyne': {
      id: '/zyne'
      path: '/zyne'
      fullPath: '/zyne'
      preLoaderRoute: typeof ZyneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording-confidentiality': {
      id: '/recording-confidentiality'
      path: '/recording-confidentiality'
      fullPath: '/recording-confidentiality'
      preLoaderRoute: typeof RecordingConfidentialityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-advisory': {
      id: '/premium-advisory'
      path: '/premium-advisory'
      fullPath: '/premium-advisory'
      preLoaderRoute: typeof PremiumAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-centre': {
      id: '/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof CommandCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-discovery-call': {
      id: '/book-discovery-call'
      path: '/book-discovery-call'
      fullPath: '/book-discovery-call'
      preLoaderRoute: typeof BookDiscoveryCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-areas': {
      id: '/advisory-areas'
      path: '/advisory-areas'
      fullPath: '/advisory-areas'
      preLoaderRoute: typeof AdvisoryAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/experts/$slug': {
      id: '/experts/$slug'
      path: '/$slug'
      fullPath: '/experts/$slug'
      preLoaderRoute: typeof ExpertsSlugRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/dashboard/zyne': {
      id: '/dashboard/zyne'
      path: '/zyne'
      fullPath: '/dashboard/zyne'
      preLoaderRoute: typeof DashboardZyneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-profile': {
      id: '/dashboard/business-profile'
      path: '/business-profile'
      fullPath: '/dashboard/business-profile'
      preLoaderRoute: typeof DashboardBusinessProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advisors': {
      id: '/dashboard/advisors'
      path: '/advisors'
      fullPath: '/dashboard/advisors'
      preLoaderRoute: typeof DashboardAdvisorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/action-plans': {
      id: '/dashboard/action-plans'
      path: '/action-plans'
      fullPath: '/dashboard/action-plans'
      preLoaderRoute: typeof DashboardActionPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/advisory-areas/$slug': {
      id: '/advisory-areas/$slug'
      path: '/$slug'
      fullPath: '/advisory-areas/$slug'
      preLoaderRoute: typeof AdvisoryAreasSlugRouteImport
      parentRoute: typeof AdvisoryAreasRoute
    }
  }
}

interface AdvisoryAreasRouteChildren {
  AdvisoryAreasSlugRoute: typeof AdvisoryAreasSlugRoute
}

const AdvisoryAreasRouteChildren: AdvisoryAreasRouteChildren = {
  AdvisoryAreasSlugRoute: AdvisoryAreasSlugRoute,
}

const AdvisoryAreasRouteWithChildren = AdvisoryAreasRoute._addFileChildren(
  AdvisoryAreasRouteChildren,
)

interface DashboardRouteChildren {
  DashboardActionPlansRoute: typeof DashboardActionPlansRoute
  DashboardAdvisorsRoute: typeof DashboardAdvisorsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBusinessProfileRoute: typeof DashboardBusinessProfileRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardZyneRoute: typeof DashboardZyneRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActionPlansRoute: DashboardActionPlansRoute,
  DashboardAdvisorsRoute: DashboardAdvisorsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBusinessProfileRoute: DashboardBusinessProfileRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardZyneRoute: DashboardZyneRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ExpertsRouteChildren {
  ExpertsSlugRoute: typeof ExpertsSlugRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsSlugRoute: ExpertsSlugRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryAreasRoute: AdvisoryAreasRouteWithChildren,
  BookDiscoveryCallRoute: BookDiscoveryCallRoute,
  CommandCentreRoute: CommandCentreRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExpertsRoute: ExpertsRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  PremiumAdvisoryRoute: PremiumAdvisoryRoute,
  PrivacyRoute: PrivacyRoute,
  RecordingConfidentialityRoute: RecordingConfidentialityRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ZyneRoute: ZyneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
