/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisoryAreasRouteImport } from './routes/advisory-areas'
import { Route as BookDiscoveryCallRouteImport } from './routes/book-discovery-call'
import { Route as CommandCentreRouteImport } from './routes/command-centre'
import { Route as ConsultantRouteImport } from './routes/consultant'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PremiumAdvisoryRouteImport } from './routes/premium-advisory'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecordingConfidentialityRouteImport } from './routes/recording-confidentiality'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ZyneRouteImport } from './routes/zyne'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminConsultantsRouteImport } from './routes/admin.consultants'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminGoogleConnectRouteImport } from './routes/admin.google-connect'
import { Route as AdminGrowthRouteImport } from './routes/admin.growth'
import { Route as AdminQualityRouteImport } from './routes/admin.quality'
import { Route as AdminRecordingsRouteImport } from './routes/admin.recordings'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdvisoryAreasSlugRouteImport } from './routes/advisory-areas.$slug'
import { Route as ApiNylasWebhookRouteImport } from './routes/api.nylas-webhook'
import { Route as ConsultantIndexRouteImport } from './routes/consultant.index'
import { Route as ConsultantAvailabilityRouteImport } from './routes/consultant.availability'
import { Route as ConsultantBookingsRouteImport } from './routes/consultant.bookings'
import { Route as ConsultantClientsRouteImport } from './routes/consultant.clients'
import { Route as ConsultantConsultationsRouteImport } from './routes/consultant.consultations'
import { Route as ConsultantEarningsRouteImport } from './routes/consultant.earnings'
import { Route as ConsultantPerformanceRouteImport } from './routes/consultant.performance'
import { Route as ConsultantProfileRouteImport } from './routes/consultant.profile'
import { Route as ConsultantSettingsRouteImport } from './routes/consultant.settings'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardActionPlansRouteImport } from './routes/dashboard.action-plans'
import { Route as DashboardAdvisorsRouteImport } from './routes/dashboard.advisors'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBusinessProfileRouteImport } from './routes/dashboard.business-profile'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardRecordingsRouteImport } from './routes/dashboard.recordings'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard.sessions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardZyneRouteImport } from './routes/dashboard.zyne'
import { Route as ExpertsSlugRouteImport } from './routes/experts.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ApiNylasMediaBookingIdRouteImport } from './routes/api.nylas-media.$bookingId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryAreasRoute = AdvisoryAreasRouteImport.update({
  id: '/advisory-areas',
  path: '/advisory-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDiscoveryCallRoute = BookDiscoveryCallRouteImport.update({
  id: '/book-discovery-call',
  path: '/book-discovery-call',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCentreRoute = CommandCentreRouteImport.update({
  id: '/command-centre',
  path: '/command-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRoute = ConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumAdvisoryRoute = PremiumAdvisoryRouteImport.update({
  id: '/premium-advisory',
  path: '/premium-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingConfidentialityRoute =
  RecordingConfidentialityRouteImport.update({
    id: '/recording-confidentiality',
    path: '/recording-confidentiality',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZyneRoute = ZyneRouteImport.update({
  id: '/zyne',
  path: '/zyne',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultantsRoute = AdminConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoogleConnectRoute = AdminGoogleConnectRouteImport.update({
  id: '/google-connect',
  path: '/google-connect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordingsRoute = AdminRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdvisoryAreasSlugRoute = AdvisoryAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdvisoryAreasRoute,
} as any)
const ApiNylasWebhookRoute = ApiNylasWebhookRouteImport.update({
  id: '/api/nylas-webhook',
  path: '/api/nylas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantIndexRoute = ConsultantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantAvailabilityRoute = ConsultantAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantBookingsRoute = ConsultantBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantClientsRoute = ConsultantClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantConsultationsRoute = ConsultantConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantEarningsRoute = ConsultantEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantPerformanceRoute = ConsultantPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantProfileRoute = ConsultantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantSettingsRoute = ConsultantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsultantRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActionPlansRoute = DashboardActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdvisorsRoute = DashboardAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessProfileRoute =
  DashboardBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordingsRoute = DashboardRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardZyneRoute = DashboardZyneRouteImport.update({
  id: '/zyne',
  path: '/zyne',
  getParentRoute: () => DashboardRoute,
} as any)
const ExpertsSlugRoute = ExpertsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExpertsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ApiNylasMediaBookingIdRoute = ApiNylasMediaBookingIdRouteImport.update({
  id: '/api/nylas-media/$bookingId',
  path: '/api/nylas-media/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/consultant': typeof ConsultantRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/google-connect': typeof AdminGoogleConnectRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/recordings': typeof AdminRecordingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/api/nylas-webhook': typeof ApiNylasWebhookRoute
  '/consultant/availability': typeof ConsultantAvailabilityRoute
  '/consultant/bookings': typeof ConsultantBookingsRoute
  '/consultant/clients': typeof ConsultantClientsRoute
  '/consultant/consultations': typeof ConsultantConsultationsRoute
  '/consultant/earnings': typeof ConsultantEarningsRoute
  '/consultant/performance': typeof ConsultantPerformanceRoute
  '/consultant/profile': typeof ConsultantProfileRoute
  '/consultant/settings': typeof ConsultantSettingsRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/nylas-media/$bookingId': typeof ApiNylasMediaBookingIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/google-connect': typeof AdminGoogleConnectRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/recordings': typeof AdminRecordingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/api/nylas-webhook': typeof ApiNylasWebhookRoute
  '/consultant/availability': typeof ConsultantAvailabilityRoute
  '/consultant/bookings': typeof ConsultantBookingsRoute
  '/consultant/clients': typeof ConsultantClientsRoute
  '/consultant/consultations': typeof ConsultantConsultationsRoute
  '/consultant/earnings': typeof ConsultantEarningsRoute
  '/consultant/performance': typeof ConsultantPerformanceRoute
  '/consultant/profile': typeof ConsultantProfileRoute
  '/consultant/settings': typeof ConsultantSettingsRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/nylas-media/$bookingId': typeof ApiNylasMediaBookingIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisory-areas': typeof AdvisoryAreasRouteWithChildren
  '/book-discovery-call': typeof BookDiscoveryCallRoute
  '/command-centre': typeof CommandCentreRoute
  '/consultant': typeof ConsultantRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/premium-advisory': typeof PremiumAdvisoryRoute
  '/privacy': typeof PrivacyRoute
  '/recording-confidentiality': typeof RecordingConfidentialityRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zyne': typeof ZyneRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/google-connect': typeof AdminGoogleConnectRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/recordings': typeof AdminRecordingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/advisory-areas/$slug': typeof AdvisoryAreasSlugRoute
  '/api/nylas-webhook': typeof ApiNylasWebhookRoute
  '/consultant/availability': typeof ConsultantAvailabilityRoute
  '/consultant/bookings': typeof ConsultantBookingsRoute
  '/consultant/clients': typeof ConsultantClientsRoute
  '/consultant/consultations': typeof ConsultantConsultationsRoute
  '/consultant/earnings': typeof ConsultantEarningsRoute
  '/consultant/performance': typeof ConsultantPerformanceRoute
  '/consultant/profile': typeof ConsultantProfileRoute
  '/consultant/settings': typeof ConsultantSettingsRoute
  '/dashboard/action-plans': typeof DashboardActionPlansRoute
  '/dashboard/advisors': typeof DashboardAdvisorsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/zyne': typeof DashboardZyneRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/nylas-media/$bookingId': typeof ApiNylasMediaBookingIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/consultant'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/consultants'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/google-connect'
    | '/admin/growth'
    | '/admin/quality'
    | '/admin/recordings'
    | '/admin/settings'
    | '/admin/users'
    | '/advisory-areas/$slug'
    | '/api/nylas-webhook'
    | '/consultant/availability'
    | '/consultant/bookings'
    | '/consultant/clients'
    | '/consultant/consultations'
    | '/consultant/earnings'
    | '/consultant/performance'
    | '/consultant/profile'
    | '/consultant/settings'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/recordings'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/admin/'
    | '/consultant/'
    | '/dashboard/'
    | '/api/nylas-media/$bookingId'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/contact'
    | '/cookies'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/consultants'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/google-connect'
    | '/admin/growth'
    | '/admin/quality'
    | '/admin/recordings'
    | '/admin/settings'
    | '/admin/users'
    | '/advisory-areas/$slug'
    | '/api/nylas-webhook'
    | '/consultant/availability'
    | '/consultant/bookings'
    | '/consultant/clients'
    | '/consultant/consultations'
    | '/consultant/earnings'
    | '/consultant/performance'
    | '/consultant/profile'
    | '/consultant/settings'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/recordings'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/admin'
    | '/consultant'
    | '/dashboard'
    | '/api/nylas-media/$bookingId'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advisory-areas'
    | '/book-discovery-call'
    | '/command-centre'
    | '/consultant'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/experts'
    | '/how-it-works'
    | '/login'
    | '/plans'
    | '/premium-advisory'
    | '/privacy'
    | '/recording-confidentiality'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/zyne'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/consultants'
    | '/admin/crm'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/google-connect'
    | '/admin/growth'
    | '/admin/quality'
    | '/admin/recordings'
    | '/admin/settings'
    | '/admin/users'
    | '/advisory-areas/$slug'
    | '/api/nylas-webhook'
    | '/consultant/availability'
    | '/consultant/bookings'
    | '/consultant/clients'
    | '/consultant/consultations'
    | '/consultant/earnings'
    | '/consultant/performance'
    | '/consultant/profile'
    | '/consultant/settings'
    | '/dashboard/action-plans'
    | '/dashboard/advisors'
    | '/dashboard/billing'
    | '/dashboard/business-profile'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/recordings'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/zyne'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/admin/'
    | '/consultant/'
    | '/dashboard/'
    | '/api/nylas-media/$bookingId'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvisoryAreasRoute: typeof AdvisoryAreasRouteWithChildren
  BookDiscoveryCallRoute: typeof BookDiscoveryCallRoute
  CommandCentreRoute: typeof CommandCentreRoute
  ConsultantRoute: typeof ConsultantRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExpertsRoute: typeof ExpertsRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  PremiumAdvisoryRoute: typeof PremiumAdvisoryRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordingConfidentialityRoute: typeof RecordingConfidentialityRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ZyneRoute: typeof ZyneRoute
  ApiNylasWebhookRoute: typeof ApiNylasWebhookRoute
  ApiNylasMediaBookingIdRoute: typeof ApiNylasMediaBookingIdRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-areas': {
      id: '/advisory-areas'
      path: '/advisory-areas'
      fullPath: '/advisory-areas'
      preLoaderRoute: typeof AdvisoryAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-discovery-call': {
      id: '/book-discovery-call'
      path: '/book-discovery-call'
      fullPath: '/book-discovery-call'
      preLoaderRoute: typeof BookDiscoveryCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-centre': {
      id: '/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof CommandCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant': {
      id: '/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-advisory': {
      id: '/premium-advisory'
      path: '/premium-advisory'
      fullPath: '/premium-advisory'
      preLoaderRoute: typeof PremiumAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording-confidentiality': {
      id: '/recording-confidentiality'
      path: '/recording-confidentiality'
      fullPath: '/recording-confidentiality'
      preLoaderRoute: typeof RecordingConfidentialityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zyne': {
      id: '/zyne'
      path: '/zyne'
      fullPath: '/zyne'
      preLoaderRoute: typeof ZyneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultants': {
      id: '/admin/consultants'
      path: '/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AdminConsultantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/google-connect': {
      id: '/admin/google-connect'
      path: '/google-connect'
      fullPath: '/admin/google-connect'
      preLoaderRoute: typeof AdminGoogleConnectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quality': {
      id: '/admin/quality'
      path: '/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recordings': {
      id: '/admin/recordings'
      path: '/recordings'
      fullPath: '/admin/recordings'
      preLoaderRoute: typeof AdminRecordingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/advisory-areas/$slug': {
      id: '/advisory-areas/$slug'
      path: '/$slug'
      fullPath: '/advisory-areas/$slug'
      preLoaderRoute: typeof AdvisoryAreasSlugRouteImport
      parentRoute: typeof AdvisoryAreasRoute
    }
    '/api/nylas-webhook': {
      id: '/api/nylas-webhook'
      path: '/api/nylas-webhook'
      fullPath: '/api/nylas-webhook'
      preLoaderRoute: typeof ApiNylasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/': {
      id: '/consultant/'
      path: '/'
      fullPath: '/consultant/'
      preLoaderRoute: typeof ConsultantIndexRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/availability': {
      id: '/consultant/availability'
      path: '/availability'
      fullPath: '/consultant/availability'
      preLoaderRoute: typeof ConsultantAvailabilityRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/bookings': {
      id: '/consultant/bookings'
      path: '/bookings'
      fullPath: '/consultant/bookings'
      preLoaderRoute: typeof ConsultantBookingsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/clients': {
      id: '/consultant/clients'
      path: '/clients'
      fullPath: '/consultant/clients'
      preLoaderRoute: typeof ConsultantClientsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/consultations': {
      id: '/consultant/consultations'
      path: '/consultations'
      fullPath: '/consultant/consultations'
      preLoaderRoute: typeof ConsultantConsultationsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/earnings': {
      id: '/consultant/earnings'
      path: '/earnings'
      fullPath: '/consultant/earnings'
      preLoaderRoute: typeof ConsultantEarningsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/performance': {
      id: '/consultant/performance'
      path: '/performance'
      fullPath: '/consultant/performance'
      preLoaderRoute: typeof ConsultantPerformanceRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/profile': {
      id: '/consultant/profile'
      path: '/profile'
      fullPath: '/consultant/profile'
      preLoaderRoute: typeof ConsultantProfileRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/settings': {
      id: '/consultant/settings'
      path: '/settings'
      fullPath: '/consultant/settings'
      preLoaderRoute: typeof ConsultantSettingsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/action-plans': {
      id: '/dashboard/action-plans'
      path: '/action-plans'
      fullPath: '/dashboard/action-plans'
      preLoaderRoute: typeof DashboardActionPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advisors': {
      id: '/dashboard/advisors'
      path: '/advisors'
      fullPath: '/dashboard/advisors'
      preLoaderRoute: typeof DashboardAdvisorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-profile': {
      id: '/dashboard/business-profile'
      path: '/business-profile'
      fullPath: '/dashboard/business-profile'
      preLoaderRoute: typeof DashboardBusinessProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recordings': {
      id: '/dashboard/recordings'
      path: '/recordings'
      fullPath: '/dashboard/recordings'
      preLoaderRoute: typeof DashboardRecordingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/zyne': {
      id: '/dashboard/zyne'
      path: '/zyne'
      fullPath: '/dashboard/zyne'
      preLoaderRoute: typeof DashboardZyneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/experts/$slug': {
      id: '/experts/$slug'
      path: '/$slug'
      fullPath: '/experts/$slug'
      preLoaderRoute: typeof ExpertsSlugRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/api/nylas-media/$bookingId': {
      id: '/api/nylas-media/$bookingId'
      path: '/api/nylas-media/$bookingId'
      fullPath: '/api/nylas-media/$bookingId'
      preLoaderRoute: typeof ApiNylasMediaBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminConsultantsRoute: typeof AdminConsultantsRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGoogleConnectRoute: typeof AdminGoogleConnectRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminQualityRoute: typeof AdminQualityRoute
  AdminRecordingsRoute: typeof AdminRecordingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminConsultantsRoute: AdminConsultantsRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGoogleConnectRoute: AdminGoogleConnectRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminQualityRoute: AdminQualityRoute,
  AdminRecordingsRoute: AdminRecordingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdvisoryAreasRouteChildren {
  AdvisoryAreasSlugRoute: typeof AdvisoryAreasSlugRoute
}

const AdvisoryAreasRouteChildren: AdvisoryAreasRouteChildren = {
  AdvisoryAreasSlugRoute: AdvisoryAreasSlugRoute,
}

const AdvisoryAreasRouteWithChildren = AdvisoryAreasRoute._addFileChildren(
  AdvisoryAreasRouteChildren,
)

interface ConsultantRouteChildren {
  ConsultantAvailabilityRoute: typeof ConsultantAvailabilityRoute
  ConsultantBookingsRoute: typeof ConsultantBookingsRoute
  ConsultantClientsRoute: typeof ConsultantClientsRoute
  ConsultantConsultationsRoute: typeof ConsultantConsultationsRoute
  ConsultantEarningsRoute: typeof ConsultantEarningsRoute
  ConsultantPerformanceRoute: typeof ConsultantPerformanceRoute
  ConsultantProfileRoute: typeof ConsultantProfileRoute
  ConsultantSettingsRoute: typeof ConsultantSettingsRoute
  ConsultantIndexRoute: typeof ConsultantIndexRoute
}

const ConsultantRouteChildren: ConsultantRouteChildren = {
  ConsultantAvailabilityRoute: ConsultantAvailabilityRoute,
  ConsultantBookingsRoute: ConsultantBookingsRoute,
  ConsultantClientsRoute: ConsultantClientsRoute,
  ConsultantConsultationsRoute: ConsultantConsultationsRoute,
  ConsultantEarningsRoute: ConsultantEarningsRoute,
  ConsultantPerformanceRoute: ConsultantPerformanceRoute,
  ConsultantProfileRoute: ConsultantProfileRoute,
  ConsultantSettingsRoute: ConsultantSettingsRoute,
  ConsultantIndexRoute: ConsultantIndexRoute,
}

const ConsultantRouteWithChildren = ConsultantRoute._addFileChildren(
  ConsultantRouteChildren,
)

interface DashboardRouteChildren {
  DashboardActionPlansRoute: typeof DashboardActionPlansRoute
  DashboardAdvisorsRoute: typeof DashboardAdvisorsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBusinessProfileRoute: typeof DashboardBusinessProfileRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardRecordingsRoute: typeof DashboardRecordingsRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardZyneRoute: typeof DashboardZyneRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActionPlansRoute: DashboardActionPlansRoute,
  DashboardAdvisorsRoute: DashboardAdvisorsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBusinessProfileRoute: DashboardBusinessProfileRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardRecordingsRoute: DashboardRecordingsRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardZyneRoute: DashboardZyneRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ExpertsRouteChildren {
  ExpertsSlugRoute: typeof ExpertsSlugRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsSlugRoute: ExpertsSlugRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvisoryAreasRoute: AdvisoryAreasRouteWithChildren,
  BookDiscoveryCallRoute: BookDiscoveryCallRoute,
  CommandCentreRoute: CommandCentreRoute,
  ConsultantRoute: ConsultantRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExpertsRoute: ExpertsRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  PremiumAdvisoryRoute: PremiumAdvisoryRoute,
  PrivacyRoute: PrivacyRoute,
  RecordingConfidentialityRoute: RecordingConfidentialityRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ZyneRoute: ZyneRoute,
  ApiNylasWebhookRoute: ApiNylasWebhookRoute,
  ApiNylasMediaBookingIdRoute: ApiNylasMediaBookingIdRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
